#!/usr/bin/env python
"""Deep content for B2, C1 and FCE. Only touches listed lessons."""
import json, os, urllib.request
PAT = os.environ["SUPABASE_PAT"]; REF = os.environ["SUPABASE_REF"]
UA = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/124.0 Safari/537.36"
def query(sql):
    body = json.dumps({"query": sql}).encode()
    req = urllib.request.Request(f"https://api.supabase.com/v1/projects/{REF}/database/query", data=body, method="POST",
        headers={"Authorization": f"Bearer {PAT}", "Content-Type": "application/json", "User-Agent": UA})
    return json.load(urllib.request.urlopen(req))
def q(s): return s.replace("'", "''")
def jq(o): return q(json.dumps(o, ensure_ascii=False))
def V(*p): return [{"term": t, "es": e} for t, e in p]
def mc(p,o,a,e=""): return ("multiple_choice",p,{"options":o,"answer":a},e)
def fb(p,t,a,e=""): return ("fill_blank",p,{"text":t,"answers":a},e)
def L(html, examples, vocab, quiz, speaking, video, guide=""):
    return [
      {"kind":"presentation","title":"Explanation","guide":guide,"html":html,"examples":examples,"videoSearch":video},
      {"kind":"practice","title":"Vocabulary & practice","vocab":vocab,"quiz":quiz},
      {"kind":"speaking","title":"Your turn","speaking":speaking},
    ]
C = {
 # ── B2 ──
 "Narrative tenses": L("<p>Combine <strong>past simple, past continuous, past perfect</strong> and <strong>past perfect continuous</strong> to tell rich stories. The past perfect (had + participle) shows what happened <em>before</em> another past action.</p>",
   ["When I arrived, the film <strong>had</strong> already <strong>started</strong>.","She was tired because she <strong>had been working</strong> all day.","While we <strong>were walking</strong>, we <strong>saw</strong> an accident."],
   V(("past perfect","had + participio"),("past perfect continuous","had been + -ing"),("by the time","para cuando"),("already","ya"),("background","trasfondo"),("sequence","secuencia")),
   [fb("Past perfect","The train ___ ___ (leave) when we got there.",["had left"]),
    mc("Which shows an earlier past action?",["past simple","past perfect","past continuous"],1)],
   ["Tell a story about a time something went wrong. Use 3 past tenses."], "narrative tenses past perfect"),
 "Reported speech": L("<p>In reported speech, tenses usually shift back one step and pronouns/time words change.</p>",
   ['"I am tired" → He said he <strong>was</strong> tired.','"I will call" → She said she <strong>would</strong> call.','"Where do you live?" → He asked where I <strong>lived</strong>.'],
   V(("said / told","dijo / le dijo"),("asked","preguntó"),("would","condicional"),("the day before","el día anterior"),("backshift","retroceso de tiempo"),("report","reportar")),
   [mc('"I love it" → She said she ___ it.',["love","loved","loves"],1),
    fb("Report the question",'He asked where I ___ (be) from.',["was"])],
   ["Report 3 things a friend told you yesterday."], "reported speech backshift"),
 "The passive voice": L("<p>Use the passive (<strong>be + past participle</strong>) when the action matters more than who does it.</p>",
   ["English <strong>is spoken</strong> here.","The bridge <strong>was built</strong> in 1900.","The report <strong>has been finished</strong>.","Mistakes <strong>were made</strong>."],
   V(("be + participle","ser + participio"),("by","por (agente)"),("active","voz activa"),("passive","voz pasiva"),("agent","agente"),("process","proceso")),
   [fb("Make it passive","They built it → It ___ ___ (build).",["was built"]),
    mc("'The cake was eaten' — who ate it?",["it's not important","the cake","we know exactly"],0)],
   ["Describe how a product is made using the passive."], "passive voice english grammar"),
 "Collocations & word formation": L("<p>Natural English relies on <strong>collocations</strong> (make a decision, do homework) and <strong>word families</strong> (decide → decision → decisive).</p>",
   ["<strong>make</strong> a decision (not 'do')","<strong>do</strong> the housework","<strong>heavy</strong> rain","<strong>strongly</strong> recommend"],
   V(("make/do","hacer (colocaciones)"),("decision → decisive","decisión → decidido"),("suffix","sufijo"),("prefix","prefijo"),("collocation","colocación"),("noun/adjective","sustantivo/adjetivo")),
   [mc("___ a decision",["do","make","take"],1),
    fb("Word form","She is very ___ (decide).",["decisive"])],
   ["Use 4 collocations with make and do in sentences."], "english collocations make do"),
 "Third conditional": L("<p>The <strong>third conditional</strong> imagines a different past: <strong>If + past perfect, would have + participle</strong>.</p>",
   ["If I <strong>had studied</strong>, I <strong>would have passed</strong>.","She wouldn't have been late if she <strong>had left</strong> earlier.","What would you have done?"],
   V(("would have + participle","habría"),("past perfect","had + participio"),("regret","arrepentimiento"),("unreal past","pasado irreal"),("missed chance","oportunidad perdida"),("hypothetical","hipotético")),
   [fb("Third conditional","If we ___ ___ (know), we would have helped.",["had known"]),
    mc("Choose correct",["If I would have known…","If I had known…","If I have known…"],1)],
   ["Talk about a past decision: what would have happened if…?"], "third conditional grammar"),
 "Wish & regrets": L("<p>Use <strong>wish + past</strong> (present regrets), <strong>wish + past perfect</strong> (past regrets), <strong>wish + would</strong> (annoyances).</p>",
   ["I <strong>wish</strong> I <strong>had</strong> more time.","I <strong>wish</strong> I <strong>hadn't said</strong> that.","I <strong>wish</strong> you <strong>wouldn't</strong> shout."],
   V(("I wish","ojalá / desearía"),("if only","si tan solo"),("regret","arrepentirse"),("annoyance","molestia"),("present wish","deseo presente"),("past wish","deseo pasado")),
   [fb("Present regret","I wish I ___ (be) taller.",["were","was"]),
    mc("Past regret: I wish I ___ harder.",["studied","had studied","study"],1)],
   ["Share 2 present wishes and 1 past regret."], "wish and regrets grammar"),
 "Mixed conditionals": L("<p>Mixed conditionals connect a past condition to a present result (or vice-versa).</p>",
   ["If I <strong>had saved</strong> money, I <strong>would be</strong> rich now.","If she <strong>were</strong> more careful, she <strong>wouldn't have crashed</strong>."],
   V(("mixed conditional","condicional mixto"),("past cause","causa pasada"),("present result","resultado presente"),("would be","estaría"),("would have","habría"),("consequence","consecuencia")),
   [mc("If I had taken the job, I ___ in London now.",["would live","would have lived","will live"],0)],
   ["Make 1 mixed conditional about your life."], "mixed conditionals"),
 "Media & technology": L("<p>Discuss media, fake news and tech trends with precise vocabulary.</p>",
   ["<strong>Fake news</strong> spreads fast.","I'm <strong>addicted to</strong> my phone.","<strong>Social media</strong> influences opinions.","Apps can <strong>track</strong> your data."],
   V(("fake news","noticias falsas"),("social media","redes sociales"),("device","dispositivo"),("privacy","privacidad"),("addicted to","adicto a"),("reliable source","fuente confiable")),
   [mc("'Reliable source' means…",["trustworthy","fake","slow"],0),
    fb("Vocabulary","Always check if the news is ___.",["reliable","true"])],
   ["Debate: are social media good or bad for society?"], "media and technology english vocabulary"),
 "Linking & discourse markers": L("<p>Organise arguments with markers: <strong>however, therefore, in addition, on the other hand, despite</strong>.</p>",
   ["It was raining; <strong>however</strong>, we went out.","He studied hard; <strong>therefore</strong>, he passed.","<strong>Despite</strong> the cost, it's worth it."],
   V(("however","sin embargo"),("therefore","por lo tanto"),("in addition","además"),("on the other hand","por otro lado"),("despite","a pesar de"),("as a result","como resultado")),
   [mc("Contrast marker:",["therefore","however","in addition"],1),
    fb("Result","He trained daily; ___, he won.",["therefore"])],
   ["Give a 1-minute opinion using 3 linkers."], "discourse markers linking words"),
 "Modals of deduction": L("<p>Speculate with <strong>must</strong> (sure it's true), <strong>can't</strong> (sure it's false), <strong>might/could/may</strong> (possible) — present and past.</p>",
   ["She <strong>must be</strong> tired.","He <strong>can't be</strong> serious.","They <strong>might have missed</strong> the bus.","It <strong>could be</strong> true."],
   V(("must be","debe (de) ser"),("can't be","no puede ser"),("might/could/may","podría"),("deduction","deducción"),("certainty","certeza"),("possibility","posibilidad")),
   [mc("The lights are off. They ___ be home.",["must","can't","should"],1),
    fb("Past deduction","She didn't answer — she ___ ___ ___ asleep.",["must have been"])],
   ["Speculate about a photo: where could it be? what might be happening?"], "modals of deduction must might can't"),
 "Formal vs. informal register": L("<p>Adapt language to the situation: contractions and phrasal verbs are informal; full forms and Latinate words are formal.</p>",
   ["Informal: <em>Can you help?</em>","Formal: <em>Could you possibly assist me?</em>","Informal: <em>get</em> → Formal: <em>receive/obtain</em>"],
   V(("formal","formal"),("informal","informal"),("polite","cortés"),("contraction","contracción"),("request","pedido"),("appropriate","apropiado")),
   [mc("Which is formal?",["Wanna come?","Would you like to attend?","Gonna go."],1)],
   ["Rewrite an informal message in a formal style."], "formal vs informal english register"),
 "Society & culture": L("<p>Debate cultural and social topics fluently.</p>",
   ["<strong>Equality</strong> matters.","<strong>Traditions</strong> shape identity.","<strong>Generation gap</strong> causes tension."],
   V(("equality","igualdad"),("tradition","tradición"),("society","sociedad"),("values","valores"),("diversity","diversidad"),("generation gap","brecha generacional")),
   [fb("Vocabulary","Respecting ___ makes a society richer.",["diversity"])],
   ["Discuss a tradition from your culture and its meaning."], "society and culture discussion english"),
 # ── C1 ──
 "Advanced tense review": L("<p>Use the full tense system precisely, including perfect continuous forms for duration and result.</p>",
   ["I<strong>'ve been meaning</strong> to call you.","By next year I<strong>'ll have been working</strong> here for a decade.","Had it not been for you…"],
   V(("perfect continuous","perfecto continuo"),("by then","para entonces"),("duration","duración"),("emphasis","énfasis"),("nuance","matiz"),("aspect","aspecto")),
   [mc("Duration up to now:",["I work here 5 years","I've been working here for 5 years"],1)],
   ["Describe a long-term project using perfect tenses."], "advanced english tenses review"),
 "Inversion & emphasis": L("<p>For emphasis (and formality), invert the subject and auxiliary after negative adverbials: <strong>Never have I…, Not only… but also…, Rarely does…</strong></p>",
   ["<strong>Never have I</strong> seen such beauty.","<strong>Not only did</strong> he win, but he also broke the record.","<strong>Rarely do</strong> we see this."],
   V(("inversion","inversión"),("never/rarely/seldom","nunca/rara vez"),("not only…but also","no solo…sino también"),("emphasis","énfasis"),("hardly…when","apenas…cuando"),("formal","formal")),
   [mc("Choose the inversion",["I never have seen…","Never have I seen…","Never I have seen…"],1)],
   ["Make 2 emphatic sentences with inversion."], "inversion for emphasis english grammar"),
 "Cleft sentences": L("<p>Highlight information with cleft structures: <strong>It was… that…</strong> and <strong>What I need is…</strong></p>",
   ["<strong>It was</strong> John <strong>who</strong> called.","<strong>What</strong> I love <strong>is</strong> the silence.","<strong>The reason</strong> I left <strong>was</strong> the noise."],
   V(("cleft sentence","oración hendida"),("It is/was…that","fue…que"),("What…is","lo que…es"),("focus","foco"),("emphasis","énfasis"),("highlight","resaltar")),
   [fb("Cleft","___ I want is some peace.",["What"])],
   ["Emphasise 2 ideas using cleft sentences."], "cleft sentences english"),
 "Idiomatic language": L("<p>Use idioms and fixed expressions naturally.</p>",
   ["It's <strong>a piece of cake</strong>. (easy)","Let's <strong>call it a day</strong>. (stop)","He <strong>spilled the beans</strong>. (told a secret)"],
   V(("a piece of cake","muy fácil"),("hit the books","ponerse a estudiar"),("under the weather","indispuesto"),("break the ice","romper el hielo"),("once in a blue moon","muy de vez en cuando"),("idiom","modismo")),
   [mc("'A piece of cake' means…",["delicious","very easy","expensive"],1)],
   ["Use 3 idioms in a short anecdote."], "common english idioms"),
 "Hedging & vague language": L("<p>Soften statements to sound diplomatic: <strong>sort of, tend to, it seems, arguably, more or less</strong>.</p>",
   ["It's <strong>sort of</strong> complicated.","People <strong>tend to</strong> agree.","<strong>It seems</strong> there's a problem."],
   V(("hedging","atenuación"),("tend to","soler"),("it seems","parece"),("arguably","posiblemente"),("more or less","más o menos"),("to some extent","hasta cierto punto")),
   [mc("Which is hedged (soft)?",["You're wrong.","I'm not sure that's quite right.","No."],1)],
   ["Disagree politely using hedging language."], "hedging vague language english"),
 "Nominalisation": L("<p>Academic style turns verbs/adjectives into nouns: <em>decide → the decision</em>, <em>fail → the failure</em>.</p>",
   ["The <strong>investigation</strong> revealed…","Her <strong>refusal</strong> surprised us.","<strong>Implementation</strong> took months."],
   V(("nominalisation","nominalización"),("decision","decisión"),("analysis","análisis"),("development","desarrollo"),("formal style","estilo formal"),("abstract noun","sustantivo abstracto")),
   [fb("Noun form","analyse → the ___",["analysis"])],
   ["Rewrite 2 sentences in a more academic, noun-heavy style."], "nominalisation academic english"),
 "Advanced collocations": L("<p>Precise, natural word partnerships make you sound fluent: <em>a deep-rooted belief, a vested interest, to pose a threat</em>.</p>",
   ["a <strong>deep-rooted</strong> belief","to <strong>pose a threat</strong>","to <strong>meet a deadline</strong>","<strong>vested</strong> interest"],
   V(("pose a threat","representar una amenaza"),("meet a deadline","cumplir un plazo"),("deep-rooted","arraigado"),("highly likely","muy probable"),("bear in mind","tener en cuenta"),("collocation","colocación")),
   [mc("___ a deadline",["meet","do","make"],0)],
   ["Use 3 advanced collocations about work or society."], "advanced english collocations"),
 "Art & literature": L("<p>Analyse and discuss art and literature with critical vocabulary.</p>",
   ["The novel <strong>explores</strong> loss.","A <strong>thought-provoking</strong> film.","The <strong>imagery</strong> is striking."],
   V(("plot","trama"),("character","personaje"),("imagery","imágenes/simbología"),("masterpiece","obra maestra"),("thought-provoking","que invita a reflexionar"),("genre","género")),
   [fb("Vocabulary","The main ___ of the story is brave.",["character"])],
   ["Describe a book or film and what theme it explores."], "discussing art and literature english"),
 "Discourse & cohesion": L("<p>Produce extended, well-organised discourse with reference words and clear paragraphing.</p>",
   ["<strong>This</strong> suggests that…","<strong>Such</strong> arguments are common.","<strong>The former… the latter…</strong>"],
   V(("cohesion","cohesión"),("reference","referencia"),("the former/latter","el primero/el último"),("furthermore","es más"),("in contrast","en contraste"),("to sum up","en resumen")),
   [mc("'The latter' refers to…",["the first thing","the second thing"],1)],
   ["Give a structured 2-minute answer with linkers and references."], "discourse cohesion academic english"),
 "Connotation & tone": L("<p>Choose words for precise effect: <em>slim</em> (positive) vs <em>skinny</em> (negative); <em>determined</em> vs <em>stubborn</em>.</p>",
   ["<strong>thrifty</strong> (positive) vs <strong>stingy</strong> (negative)","<strong>confident</strong> vs <strong>arrogant</strong>","tone: ironic, formal, sarcastic"],
   V(("connotation","connotación"),("positive/negative","positivo/negativo"),("tone","tono"),("irony","ironía"),("nuance","matiz"),("loaded word","palabra cargada")),
   [mc("Which is negative?",["slim","skinny","slender"],1)],
   ["Describe a person twice: once positively, once negatively."], "connotation and tone in english"),
 "Debating complex issues": L("<p>Argue nuanced positions fluently: concede, rebut and qualify.</p>",
   ["<strong>Admittedly</strong>, …, <strong>but</strong> …","<strong>That said</strong>, …","<strong>To play devil's advocate</strong>, …"],
   V(("admittedly","hay que admitir"),("that said","dicho esto"),("counterargument","contraargumento"),("concede","conceder"),("rebut","refutar"),("standpoint","postura")),
   [mc("To concede a point you say…",["Admittedly, …","No way.","That's stupid."],0)],
   ["Debate a controversial topic, conceding one point."], "debating complex issues fluency english"),
 "Global affairs": L("<p>Discuss politics, economics and ethics with informed vocabulary.</p>",
   ["<strong>Sustainable development</strong>","economic <strong>inequality</strong>","a <strong>humanitarian</strong> crisis"],
   V(("economy","economía"),("policy","política (medida)"),("inequality","desigualdad"),("sustainable","sostenible"),("crisis","crisis"),("human rights","derechos humanos")),
   [fb("Vocabulary","We need ___ development to protect the planet.",["sustainable"])],
   ["Discuss a current global issue and a possible solution."], "global affairs english discussion"),
 # ── FCE (B2 First exam prep) ──
 "Multiple-choice cloze (Part 1)": L("<p><strong>Reading & Use of English Part 1</strong>: choose the word that fits a gap. It tests vocabulary, collocations and phrasal verbs. Read the whole sentence first.</p>",
   ["He <strong>made</strong> an effort (not 'did').","She's <strong>keen on</strong> tennis.","Pay <strong>attention</strong> to the words around the gap."],
   V(("collocation","colocación"),("phrasal verb","phrasal verb"),("dependent preposition","preposición dependiente"),("distractor","distractor"),("context","contexto"),("gap","espacio")),
   [mc("He's interested ___ history.",["on","in","at"],1),
    mc("___ an effort",["do","make","take"],1)],
   ["Explain a strategy you'd use for Part 1."], "FCE use of english part 1 multiple choice cloze"),
 "Open cloze & word formation": L("<p><strong>Parts 2 & 3</strong>: Part 2 (open cloze) needs grammar words (articles, prepositions, auxiliaries); Part 3 transforms a root word with prefixes/suffixes.</p>",
   ["Part 2: 'It depends <strong>on</strong> you.'","Part 3: 'happy → un<strong>happiness</strong>'","Read for grammar, not just meaning."],
   V(("open cloze","cloze abierto"),("word formation","formación de palabras"),("prefix/suffix","prefijo/sufijo"),("root word","palabra raíz"),("negative prefix","prefijo negativo"),("part of speech","categoría gramatical")),
   [fb("Word formation","care → ___ (sin cuidado)",["careless"]),
    fb("Open cloze","I look forward ___ seeing you.",["to"])],
   ["Form 3 words from 'success' (succeed, successful…)."], "FCE word formation part 3"),
 "Key word transformations": L("<p><strong>Part 4</strong>: rewrite a sentence using a given key word, keeping the meaning. Use 2–5 words. Tests grammar + collocations.</p>",
   ["'I haven't seen her for years.' → It's years <strong>since</strong> I saw her.","'Maybe she's ill.' → She <strong>might be</strong> ill."],
   V(("transformation","transformación"),("keep the meaning","mantener el significado"),("2–5 words","2–5 palabras"),("key word","palabra clave"),("paraphrase","parafrasear"),("structure","estructura")),
   [mc("'It's too cold to swim.' = It's not ___ to swim.",["enough warm","warm enough","warmly enough"],1)],
   ["Transform: 'They started 5 years ago.' (using FOR)."], "FCE key word transformations part 4"),
 "The essay": L("<p><strong>Writing Part 1 (essay)</strong>: always an essay. Structure: introduction, 2 main paragraphs with reasons/examples, conclusion. Formal, balanced.</p>",
   ["Intro: state the topic.","Body: 'Firstly… Moreover…'","Conclusion: 'In conclusion, I believe…'"],
   V(("introduction","introducción"),("topic sentence","oración tema"),("furthermore","es más"),("conclusion","conclusión"),("formal","formal"),("argument","argumento")),
   [mc("An FCE essay should be…",["informal & short","formal & balanced","one paragraph"],1)],
   ["Plan an essay: 'Is technology making us lazy?' (2 points each side)."], "FCE essay writing B2 first"),
 "Email & review": L("<p><strong>Writing Part 2</strong> options include emails and reviews. Match register to the reader; a review gives an opinion + recommendation.</p>",
   ["Email: 'Thanks for your message…'","Review: 'I'd highly recommend…'","End an email: 'Best wishes,'"],
   V(("review","reseña"),("recommend","recomendar"),("semi-formal","semi-formal"),("opening/closing","apertura/cierre"),("audience","público"),("opinion","opinión")),
   [mc("A review must include…",["only facts","an opinion & recommendation","a complaint"],1)],
   ["Write the first lines of a review of a restaurant."], "FCE writing email review"),
 "Report & article": L("<p>A <strong>report</strong> is factual with headings; an <strong>article</strong> is engaging with a catchy title and direct questions to the reader.</p>",
   ["Report: 'The aim of this report is…'","Article: 'Have you ever wondered…?'","Use headings in a report."],
   V(("report","informe"),("article","artículo"),("heading","encabezado"),("engaging","atractivo"),("recommendation","recomendación"),("target reader","lector objetivo")),
   [mc("Which uses headings?",["an article","a report","an email"],1)],
   ["Brainstorm a catchy title and opening for an article."], "FCE writing report article"),
 "Listening Parts 1–2": L("<p><strong>Listening Parts 1–2</strong>: Part 1 = short extracts, multiple choice; Part 2 = sentence completion (write 1–3 words you hear). Predict before listening.</p>",
   ["Underline key words in the question.","Spelling counts in Part 2.","You hear each part twice."],
   V(("extract","fragmento"),("multiple choice","opción múltiple"),("sentence completion","completar oraciones"),("predict","predecir"),("key word","palabra clave"),("distractor","distractor")),
   [mc("In Part 2 you usually write…",["a full sentence","1–3 words","a letter A/B/C"],1)],
   ["Predict: what words could fill 'The trip lasted ___ days'?"], "FCE listening part 1 2 strategies"),
 "Listening Parts 3–4": L("<p><strong>Parts 3–4</strong>: Part 3 = multiple matching (speakers → options); Part 4 = a long interview, multiple choice. Listen for paraphrase, not exact words.</p>",
   ["Options are paraphrased, not quoted.","Eliminate wrong options.","Don't choose just because you heard a word."],
   V(("multiple matching","emparejamiento múltiple"),("interview","entrevista"),("paraphrase","paráfrasis"),("attitude","actitud"),("gist","idea general"),("eliminate","descartar")),
   [mc("Correct answers are usually…",["exact words from audio","paraphrased ideas"],1)],
   ["Why is it risky to pick the option with the same words you heard?"], "FCE listening part 3 4"),
 "Exam-day listening strategies": L("<p>Manage time and nerves: read questions first, predict, and never leave blanks — guess if unsure.</p>",
   ["Read ahead during pauses.","Always write something.","Stay calm if you miss one — move on."],
   V(("predict","predecir"),("guess","adivinar"),("stay calm","mantener la calma"),("time management","gestión del tiempo"),("focus","concentración"),("blank","en blanco")),
   [mc("If you don't know an answer, you should…",["leave it blank","make your best guess"],1)],
   ["Share your top 2 tips for staying calm in a listening exam."], "exam listening tips strategies"),
 "Interview & long turn": L("<p><strong>Speaking Parts 1–2</strong>: Part 1 = personal questions; Part 2 = speak alone for 1 minute comparing two photos. Compare AND speculate.</p>",
   ["'Both photos show…'","'Whereas the first…, the second…'","'They might be… because…'"],
   V(("compare","comparar"),("speculate","especular"),("whereas","mientras que"),("in the foreground","en primer plano"),("fluency","fluidez"),("long turn","turno extendido")),
   [mc("In Part 2 you should…",["describe every detail","compare and speculate"],1)],
   ["Compare two photos of people working for 1 minute."], "FCE speaking part 2 long turn"),
 "Collaborative task": L("<p><strong>Speaking Part 3</strong>: discuss options with a partner, then reach a decision. Use interactive language to involve them.</p>",
   ["'What do you think about…?'","'I see your point, but…'","'Shall we say…?'"],
   V(("collaborate","colaborar"),("negotiate","negociar"),("reach a decision","llegar a una decisión"),("involve","involucrar"),("agree/disagree","acordar/discrepar"),("suggestion","sugerencia")),
   [mc("To involve your partner you ask…",["'What do you think?'","'I'm right.'","nothing"],0)],
   ["Decide with a partner the best way to learn English."], "FCE speaking part 3 collaborative task"),
 "Discussion & fluency": L("<p><strong>Speaking Part 4</strong>: develop opinions on broader questions. Don't give one-word answers — explain and give examples.</p>",
   ["'In my view…, for example…'","'It depends on…'","Extend every answer with a reason."],
   V(("develop an answer","desarrollar"),("give reasons","dar razones"),("for instance","por ejemplo"),("it depends","depende"),("fluency","fluidez"),("hesitation","vacilación")),
   [mc("A good Part 4 answer is…",["one word","extended with reasons"],1)],
   ["Answer: 'Is it better to study alone or in groups?' Give reasons."], "FCE speaking part 4 fluency"),
}
def main():
    titles=list(C.keys()); inlist=",".join(f"'{q(t)}'" for t in titles)
    lessons={r["title"]:r["id"] for r in query(f"select id,title from public.lessons where title in ({inlist})")}
    done=0
    for title,blocks in C.items():
        lid=lessons.get(title)
        if not lid: print("MISSING:",title); continue
        query(f"delete from public.lesson_blocks where lesson_id='{lid}'")
        query(f"delete from public.quizzes where title='L· {q(title[:40])}'")
        for idx,b in enumerate(blocks):
            content={k:b[k] for k in ("guide","html","examples","vocab","speaking","tip","videoSearch") if b.get(k)}
            if b.get("quiz"):
                qid=query(f"insert into public.quizzes (title,description,is_shared) values ('L· {q(title[:40])}','{q(b.get('title',''))}',true) returning id")[0]["id"]
                vals=[f"('{qid}','{k}','{q(p)}','{jq(d)}'::jsonb,'{q(e)}',1,{i})" for i,(k,p,d,e) in enumerate(b["quiz"])]
                query("insert into public.quiz_questions (quiz_id,kind,prompt,data,explanation,points,sort_order) values "+", ".join(vals))
                content["quizId"]=qid
            dur={"presentation":15,"practice":20,"speaking":15}.get(b["kind"],10)
            query(f"insert into public.lesson_blocks (lesson_id,kind,title,duration_min,sort_order,content) values ('{lid}','{b['kind']}','{q(b['title'])}',{dur},{idx},'{jq(content)}'::jsonb)")
        done+=1
    print(f"Deep content written for {done} lessons.")
if __name__=="__main__": main()
